version: "3.7"
services:
  clrernet-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: 1234
        PYTHON_VERSION: 3.8.4
        TORCH_VERSION: 1.12.1+cu116
        TORCHVISION_VERSION: 0.13.1
        TORCH_CUDA_ARCH_LIST: 7.5;8.0;8.6
        MIM_VERSION: 0.3.3
        MMCV_VERSION: 1.7.0
        MMDET_VERSION: 2.28.0
    environment:
      - DISPLAY=host.docker.internal:0.0
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/work
      - $HOME/dataset:/work/dataset
    dns:
      - 8.8.8.8  # Google DNS
      - 8.8.4.4
    tty: true
    shm_size: "16gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, compute]
